apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trivy-ui-ingress
  namespace: trivy-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: authelia-authelia-auth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - trivy0213.kro.kr
      secretName: trivy-ui-tls
  rules:
    - host: trivy0213.kro.kr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trivy-ui
                port:
                  number: 80
