apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-runner-secret
  namespace: gitea
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gitea-runner-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: gitea
        property: runner_token
