apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vault/grafana-admin-password.yaml
- ingress.yaml

configMapGenerator:
- name: grafana-dashboard-argocd
  files:
  - dashboards/argocd.json
  options:
    labels:
      grafana_dashboard: "1"
- name: grafana-dashboard-cert-manager
  files:
  - dashboards/cert-manager.json
  options:
    labels:
      grafana_dashboard: "1"
- name: grafana-dashboard-cloudnative-pg
  files:
  - dashboards/cloudnative-pg.json
  options:
    labels:
      grafana_dashboard: "1"
- name: grafana-dashboard-coredns
  files:
  - dashboards/coredns.json
  options:
    labels:
      grafana_dashboard: "1"
- name: grafana-dashboard-falco
  files:
  - dashboards/falco.json
  options:
    labels:
      grafana_dashboard: "1"
- name: grafana-dashboard-k8s-global
  files:
  - dashboards/kubernetes-views-global.json
  options:
    labels:
      grafana_dashboard: "1"
- name: grafana-dashboard-k8s-namespaces
  files:
  - dashboards/kubernetes-views-namespaces.json
  options:
    labels:
      grafana_dashboard: "1"
- name: grafana-dashboard-k8s-pods
  files:
  - dashboards/kubernetes-views-pods.json
  options:
    labels:
      grafana_dashboard: "1"
- name: grafana-dashboard-loki-logs
  files:
  - dashboards/loki-logs-app.json
  options:
    labels:
      grafana_dashboard: "1"
- name: grafana-dashboard-loki-metrics
  files:
  - dashboards/loki-metrics.json
  options:
    labels:
      grafana_dashboard: "1"
- name: grafana-dashboard-minio
  files:
  - dashboards/minio.json
  options:
    labels:
      grafana_dashboard: "1"
- name: grafana-dashboard-node-exporter
  files:
  - dashboards/node-exporter-full.json
  options:
    labels:
      grafana_dashboard: "1"
- name: grafana-dashboard-traefik
  files:
  - dashboards/traefik-custom.json
  options:
    labels:
      grafana_dashboard: "1"
- name: grafana-dashboard-trivy
  files:
  - dashboards/trivy-operator.json
  options:
    labels:
      grafana_dashboard: "1"

generatorOptions:
  disableNameSuffixHash: true
