apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # argocd.yaml files은 수동으로 관리 (순환 참조 방지)
  - namespace.yaml
  - external-secret.yaml
  - vault/velero-ui-secret.yaml
  - ingress.yaml
